print("Es una primera prueba de código en Python.")
print("¡Hola, mundo!")
print("Este es un ejemplo de cómo imprimir texto en la consola.")
print("Python es un lenguaje de programación muy popular y versátil.")
print("Salir del programa.")
print("no me salgo aún")
print ("¡Hasta luego!")